import { PLATFORM } from "@/stores/settings";

export const Keys = {
  // MAC_COMMAND: "⌘",
  // MAC_OPTION: "⌥",
  // MAC_CONTROL: "⌃",
  SHIFT: "⇧",
  ENTER: "⏎",
  DELETE: "⌫",
  TAB: "⇥",
  SPACE: "␣",
  ARROW_UP: "↑",
  ARROW_DOWN: "↓",
  ARROW_LEFT: "←",
  ARROW_RIGHT: "→",
  PAGE_UP: "⇞",
  PAGE_DOWN: "⇟",
  HOME: "↖",
  END: "↘",
  BACKSPACE: "⌫",
  CAPS_LOCK: "⇪",
  PRINT_SCREEN: "PrtSc",
  SCROLL_LOCK: "⇳",
  PAUSE_BREAK: "Pause",
  INSERT: "Ins",
  NUM_LOCK: "Num",
  CONTEXT_MENU: "Menu",
  WINDOWS: "⊞",
  META: PLATFORM === "macos" ? "⌘" : "Win",
  ALT: PLATFORM === "macos" ? "⌥" : "Alt",
  CONTROL_OR_META: PLATFORM === "macos" ? "⌘" : "Ctrl",
} as const;
